api/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (ChipStackPokerUpdateJson)


urlpatterns = [
    url(r'^chipstack/(?P<session_id>\d+)/$', ChipStackPokerUpdateJson.as_view(), name='chipstack'),
]

pokersessions/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (PokerSessionIndexView, CreatePokerSessionView,
                    AddPokerSessionUpdateView, DeletePokerSessionUpdateView,
                    StartPokerSessionView, ActivePokerSessionView, PokerSessionUserView,
                    PokerSessionDetailView, DeletePokerSessionView)

import pokersessions


urlpatterns = [
    url(r'^$', PokerSessionIndexView.as_view(), name='index'),
    url(r'^(?P<user_id>\d+)/$', PokerSessionUserView.as_view(), name='view'),
    url(r'^create/$', CreatePokerSessionView.as_view(), name='create'),
    url(r'^edit/(?P<session_id>\d+)/add/$', AddPokerSessionUpdateView.as_view(), name='add_update'),
    url(r'^edit/delete/(?P<update_id>\d+)/$', DeletePokerSessionUpdateView.as_view(), name='delete_update'),
    url(r'^start/$', StartPokerSessionView.as_view(), name='start'),
    url(r'^active/$', ActivePokerSessionView.as_view(), name='active'),
    url(r'^(?P<session_id>\d+)/detail/$', PokerSessionDetailView.as_view(), name='detail'),
    url(r'^(?P<session_id>\d+)/delete/$', DeletePokerSessionView.as_view(), name='delete'),
    url(r'^(?P<session_id>\d+)/edit/$', pokersessions.views.edit_poker_session, name='edit'),
]

trackpoker/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from trackpoker import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^pokersessions/', include('pokersessions.urls', namespace='pokersessions')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^locations/', include('locations.urls', namespace='locations')),
    url(r'^games/', include('games.urls', namespace='games')),
    url(r'^$', views.index, name='index'),
]

pokersessions/models.py
from decimal import *

from django.db import models

from datetime import datetime, timedelta
from pytz import timezone
import pytz

from accounts.models import User
from locations.models import Location
from games.models import Game


class PokerSessionManager(models.Manager):

    def __init__(self, *args, **kwargs):
        super(PokerSessionManager, self).__init__(*args, **kwargs)


# Create your models here.
class PokerSession(models.Model):
    user = models.ForeignKey(User)
    location = models.ForeignKey(Location)
    active = models.BooleanField(default=False)
    game = models.ForeignKey(Game)
    public = models.BooleanField(default=False)
    get_latest_by = 'time'
    deleted = models.BooleanField(default=False)

    def session_updates(self):
        sessions = PokerSessionUpdate.objects.filter(poker_session=self).order_by('time')
        return sessions

    def start_time(self):
        try:
            start_time = self.session_updates()[0].time
        except IndexError:
            start_time = None
        return start_time

    def end_time(self):
        try:
            end_time = self.session_updates().latest('time').time
        except IndexError:
            end_time = None
        return end_time

    def total_mins_played(self):
        return self.end_time() - self.start_time()

    def all_buy_ins(self):
        return self.session_updates().exclude(buy_in__isnull=True)

    def all_chip_stacks(self):
        return self.session_updates().exclude(chip_stack__isnull=True)

    def net(self):
        return self.all_chip_stacks().latest('time').chip_stack - self.all_buy_ins().latest('time').buy_in

    def short_title(self):
        return '{0} @ {1}'.format(self.game.short_str(), self.location)

    def __str__(self):
        return self.short_title()


class PokerSessionUpdate(models.Model):
    poker_session = models.ForeignKey(PokerSession)
    time = models.DateTimeField(
        blank=False
    )
    chip_stack = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        null=True,
        blank=True
    )
    buy_in = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        null=True,
        blank=True,
    )
    comment = models.TextField(blank=True, null=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return "Poker Session Update - poker_session.id = {0}".format(self.poker_session.id)

    def all_str(self):
        s = "poker_session = {0} | time = {1} | chip_stack = {2} | buy_in = {3} | comment = {4}".format(
                self.poker_session, self.time, self.chip_stack, self.buy_in, self.comment,
            )
        return s

    def chip_stack_pretty(self):
        if (self.chip_stack == None):
            return ""
        return "{0}{1:,}".format(
            self.poker_session.game.currency.symbol,
            float(str(self.chip_stack))
        )

    def buy_in_pretty(self):
        if (self.buy_in == None):
            return ""
        return "{0}{1:,}".format(
            self.poker_session.game.currency.symbol,
            float(str(self.buy_in))
        )

pokersessions/forms.py
from django import forms

from .models import ( PokerSession, PokerSessionUpdate)
from locations.models import Location
from games.models import Game

class PokerSessionForm(forms.ModelForm):
   class Meta:
      model = PokerSession
      fields = ['location', 'game', 'public']

class PokerSessionUpdateForm(forms.Form):
   time = forms.DateTimeField(
         widget=forms.TextInput(attrs={
                  'placeholder': 'YYYY-MM-DD HH:mm',
         }),
      )
   buy_in = forms.DecimalField(
         max_digits=15,
         decimal_places=2,
         required=False,
         widget=forms.TextInput(attrs={
                  'placeholder': 'Total Buy-In',
         }),
      )
   chip_stack = forms.DecimalField(
         max_digits=15,
         decimal_places=2,
         required=False,
         widget=forms.TextInput(attrs={
                  'placeholder': 'Chip Stack',
         }),
      )
   comment = forms.CharField(
         required = False,
         max_length=256,
      )

class PokerSessionCreateForm(forms.Form):
   time = forms.DateTimeField(
         widget=forms.TextInput(attrs={
                  'placeholder': 'YYYY-MM-DD HH:mm',
         }),
      )
   location = forms.ModelChoiceField(
         queryset=Location.objects.all(),
         empty_label=None,
         required=True,
         label="Location"
      )
   game = forms.ModelChoiceField(
         queryset=Game.objects.all(),
         empty_label=None,
         required=True,
         label="Game"
      )
   buy_in = forms.DecimalField(
         max_digits=15,
         decimal_places=2,
         required=True,
         label="Total Buy in"
      )
   public = forms.BooleanField(
         required=False,
         initial=True,
      )

class PokerSessionStartForm(forms.Form):
   location = forms.ModelChoiceField(
         queryset=Location.objects.all(),
         empty_label=None,
         required=True,
         label="Location"
      )
   game = forms.ModelChoiceField(
         queryset=Game.objects.all(),
         empty_label=None,
         required=True,
         label="Game"
      )
   buy_in = forms.DecimalField(
         max_digits=15,
         decimal_places=2,
         required=True,
         label="Buy in"
      )

class ActivePokerSessionUpdateForm(forms.Form):
   buy_in = forms.DecimalField(
         max_digits=15,
         decimal_places=2,
         required=False,
         label="Total Buy in",
      )
   chip_stack = forms.DecimalField(
         max_digits=15,
         decimal_places=2,
         required=False,
         label="Current Chip Stack",
      )
   comment = forms.CharField(
         required = False,
         max_length=256,
      )

pokersessions/views.py
from datetime import datetime, timedelta
from pytz import timezone
import pytz

import json

from django.shortcuts import render, redirect
from django.contrib.auth.forms import PasswordResetForm
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db import IntegrityError, transaction
from django.forms.formsets import formset_factory

from accounts.models import User
from .models import PokerSession, PokerSessionUpdate
from .forms import (PokerSessionForm, PokerSessionUpdateForm, PokerSessionStartForm,
                    PokerSessionCreateForm, ActivePokerSessionUpdateForm)

# Create your views here.

class PokerSessionIndexView(LoginRequiredMixin, ListView):
    template_name = 'pokersessions/index.html'
    model = PokerSession

    def get_queryset(self):
        user = self.request.user
        object_list = self.model.objects.filter(user=user)
        return object_list

class PokerSessionUserView(ListView):
    template_name = 'pokersessions/view.html'
    model = PokerSession

    def get_queryset(self):
        user = User.objects.get(pk=self.kwargs['user_id'])
        object_list = self.model.objects.filter(user=user).exclude(public=False)
        return object_list

class CreatePokerSessionView(LoginRequiredMixin, FormView):
    template_name = "pokersessions/create.html"
    form_class = PokerSessionCreateForm
    success_url = reverse_lazy('pokersessions:index')

    def form_valid(self, form):
        resp = super(CreatePokerSessionView, self).form_valid(form)
        clean = form.cleaned_data
        user = self.request.user
        location = clean['location']
        game = clean['game']
        public = clean['public']

        poker_session = PokerSession(user=user, location=location, game=game, active=False, public=public)
        poker_session.save()

        time = clean['time']
        buy_in = clean['buy_in']
        tzinfo = timezone(location.timezone)
        time = time.replace(tzinfo=tzinfo).astimezone(pytz.utc)

        update = PokerSessionUpdate(poker_session=poker_session, time=time,
                buy_in=buy_in, chip_stack=buy_in)
        update.save()

        messages.success(self.request, '{0} Created'.format(poker_session))

        return redirect('pokersessions:edit', session_id=poker_session.id)

@login_required
def edit_poker_session(request, session_id):
    user = request.user

    # Create the formset, specifying the form and formset we want to use.
    UpdateFormSet = formset_factory(PokerSessionUpdateForm)
    poker_session = PokerSession.objects.get(pk=session_id)
    tz = timezone(poker_session.location.timezone)

    if(poker_session.user.id != user.id):
        messages.error(request, 'Not the owner of the poker session')
        return redirect('pokersession:index')

    if(request.method == "POST"):
        poker_session_form = PokerSessionForm(request.POST)
        update_formset = UpdateFormSet(request.POST)

        if(poker_session_form.is_valid() and update_formset.is_valid()):
            poker_session.location = poker_session_form.cleaned_data['location']
            poker_session.game = poker_session_form.cleaned_data['game']
            poker_session.public = poker_session_form.cleaned_data['public']

            poker_session.save()

            new_updates = []

            for update_form in update_formset:
                clean = update_form.cleaned_data
                time = clean.get('time')
                if time is None:
                    continue

                time = tz.localize(time.replace(tzinfo=None)).astimezone(pytz.utc)

                chip_stack = clean['chip_stack']
                buy_in = clean['buy_in']
                comment = clean['comment']
                if not (chip_stack is None and buy_in is None and comment is None):
                    new_updates.append(PokerSessionUpdate(
                            poker_session=poker_session,
                            time=time,
                            chip_stack=chip_stack,
                            buy_in=buy_in,
                            comment=comment
                        ))

            try:
                with transaction.atomic():
                    PokerSessionUpdate.objects.filter(poker_session=poker_session).delete()
                    PokerSessionUpdate.objects.bulk_create(new_updates)
                    messages.success(request, 'Poker Session Updated')

            except IntegrityError:
                messages.error(request, "There was an error with the update")

        else:
            context = {
                'poker_session_form': poker_session_form,
                'update_formset': update_formset,
                'poker_session': poker_session,
            }

            return render(request, 'pokersessions/edit_all.html', context)

    updates = poker_session.session_updates()
    update_info = []
    for update in updates:
        time = update.time.astimezone(tz)
        update_info.append({
            'time': time.strftime("%Y-%m-%d %H:%M"),
            'buy_in': update.buy_in,
            'chip_stack': update.chip_stack,
            'comment': update.comment
        })
    poker_session_form = PokerSessionForm(instance=poker_session)
    update_formset = UpdateFormSet(initial=update_info)

    context = {
        'poker_session_form': poker_session_form,
        'update_formset': update_formset,
        'poker_session': poker_session,
    }

    return render(request, 'pokersessions/edit.html', context)



class AddPokerSessionUpdateView(LoginRequiredMixin, FormView):
    template_name = "pokersessions/update_add.html"
    form_class = PokerSessionUpdateForm
    success_url = reverse_lazy('pokersessions:index')
    poker_session = None

    def get(self, request, *args, **kwargs):
        session_id = self.kwargs['session_id']
        self.poker_session = PokerSession.objects.get(pk=session_id)

        return super(AddPokerSessionUpdateView, self).get(request, args, kwargs)

    def form_valid(self, form):
        resp = super(AddPokerSessionUpdateView, self).form_valid(form)
        clean = form.cleaned_data
        time = clean['time']
        buy_in = clean['buy_in']
        chip_stack = clean['chip_stack']
        comment = clean['comment']


        session_id = self.kwargs['session_id']
        poker_session = PokerSession.objects.get(pk=session_id)

        tzinfo = timezone(poker_session.location.timezone)
        time = time.replace(tzinfo=tzinfo).astimezone(pytz.utc)

        update = PokerSessionUpdate(poker_session=poker_session, time=time,
                buy_in=buy_in, chip_stack=chip_stack, comment=comment)
        update.save()

        messages.success(self.request, '{0} added to {1}'.format(update, poker_session))

        if('add_return' in self.request.POST):
            return HttpResponseRedirect(reverse('pokersessions:edit', kwargs={'session_id':session_id}))

        return HttpResponseRedirect(reverse('pokersessions:add_update', kwargs={'session_id':session_id}))

    def get_initial(self):
        session_id = self.kwargs['session_id']
        poker_session = PokerSession.objects.get(pk=session_id)
        return { "time": poker_session.end_time() }

class DeletePokerSessionView(LoginRequiredMixin, DeleteView):

    def get_object(self):
        update_id = self.kwargs['session_id']
        obj = PokerSession.objects.get(pk=update_id)
        return obj

    def get(self, request, *args, **kwargs):
        return super(DeletePokerSessionView,self).post(request, args, kwargs)

    def delete(self, request, *args, **kwargs):
        poker_session = self.get_object()
        user = self.request.user
        if(poker_session.user.id == user.id):
            poker_session.delete()
            messages.success(request, 'Poker Session Deleted')
            return HttpResponseRedirect(reverse('pokersessions:index'))

        messages.error(request, 'Not the owner of the Poker Session')
        return HttpResponseRedirect(reverse('pokersession:index'))

class DeletePokerSessionUpdateView(LoginRequiredMixin, DeleteView):

    def get_object(self):
        update_id = self.kwargs['update_id']
        obj = PokerSessionUpdate.objects.get(pk=update_id)
        return obj

    def get(self, request, *args, **kwargs):
        return super(DeletePokerSessionUpdateView,self).post(request, args, kwargs)

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        user = self.request.user
        if(obj.poker_session.user.id == user.id):
            poker_session = obj.poker_session
            obj.delete()
            messages.success(request, 'Poker Session Update Deleted')
            return HttpResponseRedirect(reverse('pokersessions:edit', kwargs={'session_id':poker_session.id}))
        else:
            messages.error(request, 'Not the owner of the Poker Session Update')
            return HttpResponseRedirect(reverse('pokersession:index'))

class StartPokerSessionView( LoginRequiredMixin, FormView ):

    template_name = "pokersessions/start.html"
    form_class = PokerSessionStartForm
    success_url = reverse_lazy('pokersessions:active')

    def get(self, request, *args, **kwargs):
        #check if user has an active session already
        user = request.user
        poker_session_count = PokerSession.objects.filter(active=True).filter(user=user).count()
        if(poker_session_count > 0):
            messages.error(request, 'User already has an active session')
            return HttpResponseRedirect(reverse('pokersessions:active'))

pokersessions/templates/pokersessions/active.html
{% extends 'base.html' %}

{% block title %}pokersessions/active{% endblock %}

{% block content %}
{% load tz %}
    <h2>pokersessions/active</h2>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class='btn' type="submit">Submit Update</button>
        <button class='btn' type="submit" name='end_session'>Submit Update And End Session</button>
      </form>
      <h2><center>Updates<center></h2>
      <table class="table">
        <thead>
          <tr>
            <th>Date Time (Local)</th>
            <th>Buyin</th>
            <th>Chip Stack</th>
            <th>Comment</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for update in view.active_session.session_updates %}
          <tr>
            <td>
              {% timezone update.poker_session.location.timezone %}
                {{ update.time|date:"Y-m-d H:i" }}
              {% endtimezone %}
            </td>
            <td>
              {{ update.buy_in }}
            </td>
            <td>
              {{ update.chip_stack }}
            </td>
            <td>
              {{ update.comment }}
            </td>
            <td>
              edit
            </td>
            <td>
              <a href="{% url 'pokersessions:delete_update' update.id %}">
                delete
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
{% endblock %}

pokersessions/templates/pokersessions/add_session.html
{% extends 'base.html' %}

{% block title %}pokersessions/add{% endblock %}

{% block content %}
{% load tz %}
    <h2>pokersessions/add</h2>
      <form method="post">
        {% csrf_token %}
        {% localtime off %}
        {{ form.as_p }}
        {% endlocaltime %}
        <button type="submit">Add Session</button>
      </form>
{% endblock %}

pokersessions/templates/pokersessions/batch_session.html
{% extends 'base.html' %}

{% block title %}pokersessions/current{% endblock %}

{% block content %}
    <h2>pokersessions/current</h2>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Session</button>
      </form>
{% endblock %}

pokersessions/templates/pokersessions/create.html
{% extends 'base.html' %}

{% block title %}pokersessions/create{% endblock %}

{% block content %}
    <h2>pokersessions/create</h2>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Poker Session</button>
      </form>
{% endblock %}

pokersessions/templates/pokersessions/current_session.html
{% extends 'base.html' %}

{% block title %}pokersessions/update{% endblock %}

{% block content %}
    <h1>pokersessions/update</h1>
    <h2>Poker Session Started at {{ view.current_poker_session.location }}
     on {{ view.current_poker_session.started|date:"Y-m-d" }}
    </h2>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit Update</button>
      </form>
{% endblock %}

pokersessions/templates/pokersessions/detail.html
{% extends 'base.html' %}

{% block title %}pokersessions/detail{% endblock %}
{% block head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment-with-locales.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
{% endblock %}
{% block content %}
{% load tz %}
    <h2>pokersessions/detail</h2>
    <div width="100%">
      <canvas id="chart"></canvas>
    </div>
      <table class="table">
        <thead>
          <tr>
            <th>Date Time (Local)</th>
            <th>Buyin</th>
            <th>Chip Stack</th>
            <th>Comment</th>
          </tr>
        </thead>
        <tbody>
          {% for update in view.poker_session.session_updates %}
          <tr>
            <td>
              {% timezone update.poker_session.location.timezone %}
                {{ update.time|date:"Y-m-d H:i" }}
              {% endtimezone %}
            </td>
            <td>
              {{ update.buy_in_pretty }}
            </td>
            <td>
              {{ update.chip_stack_pretty }}
            </td>
            <td>
              {{ update.comment }}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
{% endblock %}
{% block js %}
<script>
window.chartColors = {
	red: 'rgb(255, 99, 132)',
	orange: 'rgb(255, 159, 64)',
	yellow: 'rgb(255, 205, 86)',
	green: 'rgb(75, 192, 192)',
	blue: 'rgb(54, 162, 235)',
	purple: 'rgb(153, 102, 255)',
	grey: 'rgb(231,233,237)'
};

window.randomScalingFactor = function() {
	return (Math.random() > 0.5 ? 1.0 : -1.0) * Math.round(Math.random() * 100);
}

var timeFormat = 'YYYY-MM-DD HH:mm';

function newDate(days) {
	return moment().add(days, 'd').toDate();
}
function newDateString(days) {
	return moment().add(days, 'd').format(timeFormat);
}
function newTimestamp(days) {
	return moment().add(days, 'd').unix();
}

var color = Chart.helpers.color;
var config = {
	type: 'line',
	data: {
		datasets: [{
  		label: "Chip-Stacks",
			backgroundColor: color(window.chartColors.blue).alpha(0.5).rgbString(),
			borderColor: window.chartColors.green,
			fill: false,
			data: {{ view.ChipStackUpdatesChartJson|safe }},
			lineTension: 0,
		}, {
			label: "Buy-in",
			backgroundColor: color(window.chartColors.red).alpha(0.5).rgbString(),
			borderColor: window.chartColors.red,
			fill: false,
			data: {{ view.BuyInUpdatesChartJson|safe }},
			lineTension: 0,
		}],
	},
  options: {
            title:{
                text: "Chip Stack and Buy-in over Sessions"
            },
		scales: {
			xAxes: [{
				type: "time",
				time: {
					format: timeFormat,
					// round: 'day'
					tooltipFormat: 'll HH:mm'
				},
				scaleLabel: {
					display: true,
					labelString: 'Date'
				}
			}, ],
			yAxes: [{
				scaleLabel: {
					display: true,
					labelString: '{{ view.poker_session.game.currency.short_str }}'
				}
			}]
		},
	}
};

window.onload = function() {
	var ctx = document.getElementById("chart").getContext("2d");
	window.myLine = new Chart(ctx, config);
};
</script>
{% endblock %}

pokersessions/templates/pokersessions/index.html
{% extends 'base.html' %}

{% block title %}Pokersessions/Index{% endblock %}

{% block content %}
{% load tz %}
    <h2>pokersessions/index</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Start Date</th>
                <th>Location</th>
                <th>Game</th>
                <th>Total Mins Played</th>
                <th>Net</th>
                <th>Public</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
                {% for poker_session in object_list %}
                {% if poker_session.active %}
                <tr class="bg-success">
                {% else %}
                <tr>
                {% endif %}
                    <td>
                    {% timezone poker_session.location.timezone %}
                    <a href="{%url 'pokersessions:detail' poker_session.id %}">
                        {{ poker_session.start_time|date:"Y-m-d H:i" }}
                    </a>
                    {% endtimezone %}
                    </td>
                    <td>{{ poker_session.location }}</td>
                    <td>{{ poker_session.game }}</td>
                    <td>{{ poker_session.total_mins_played }}</td>
                    <td>{{ poker_session.net }}</td>
                    <td>{{ poker_session.public }}</td>
                    <td><a href="{% url 'pokersessions:edit' poker_session.id %}">edit</a></td>
                    <td><a href="{% url 'pokersessions:delete' poker_session.id %}" id="delete">delete</a></td>
                </tr>
                {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block js %}


{% endblock %}

pokersessions/templates/pokersessions/start.html
{% extends 'base.html' %}

{% block title %}pokersessions/start{% endblock %}

{% block content %}
    <h2>pokersessions/start</h2>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class='btn' type="submit">Start Session</button>
      </form>
{% endblock %}

pokersessions/templates/pokersessions/update_add.html
{% extends 'base.html' %}

{% block title %}pokersessions/AddUpdateToSession{% endblock %}

{% block content %}
    <h2>pokersessions/AddUpdateToSession</h2>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class='btn' name='add_return'>Add Update and Return</button>
        <button type="submit" class='btn' name='add_multiple'>Add Another Update</button>
      </form>
{% endblock %}

pokersessions/templates/pokersessions/update_edit.html
{% extends 'base.html' %}

{% block title %}pokersessions/update/edit{% endblock %}

{% block content %}
{% load tz %}
    <h2>pokersessions/update/edit</h2>
      <form method="post">
        {% csrf_token %}
        {% timezone poker_session.location.timezone %}
        {{ form.as_p }}
        {% endtimezone %}
        <button type="submit">Edit Update</button>
      </form>
{% endblock %}

pokersessions/templates/pokersessions/view.html
{% extends 'base.html' %}

{% block title %}Poker Sessions{% endblock %}

{% block content %}
{% load tz %}
    <h2>Poker Sessions for {{ user.email }}</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Start Time (Local)</th>
                <th>Location</th>
                <th>Game</th>
                <th>Total Mins Played</th>
                <th>Net</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
                {% for poker_session in object_list %}
                {% if poker_session.active %}
                <tr class="bg-success">
                {% else %}
                <tr>
                {% endif %}
                    <td>
                    {% timezone poker_session.location.timezone %}
                    {{ poker_session.start_time|date:"Y-m-d H:i" }}
                    {% endtimezone %}
                    </td>
                    <td>{{ poker_session.location }}</td>
                    <td>{{ poker_session.game }}</td>
                    <td>{{ poker_session.total_mins_played }}</td>
                    <td>{{ poker_session.net }}</td>
                    <td><a href="{% url 'pokersessions:detail' poker_session.id %}">detail</a></td>
                </tr>
                {% endfor %}
        </tbody>
    </table>
{% endblock %}