api/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (ChipStackPokerUpdateJson)


urlpatterns = [
    url(r'^chipstack/(?P<session_id>\d+)/$', ChipStackPokerUpdateJson.as_view(), name='chipstack'),
]

games/urls.py
from django.conf.urls import url
from django.contrib import admin

import games.views


urlpatterns = [
    url(r'^list/$', games.views.list_view, name='list'),
    url(r'^delete/(?P<pk>\d+)$', games.views.delete, name='delete'),
]

trackpoker/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from trackpoker import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^pokersessions/', include('pokersessions.urls', namespace='pokersessions')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^locations/', include('locations.urls', namespace='locations')),
    url(r'^games/', include('games.urls', namespace='games')),
    url(r'^$', views.index, name='index'),
]

games/models.py
from django.db import models

from accounts.models import User

# Create your models here.

class Currency(models.Model):
    name = models.CharField(max_length=100)
    symbol = models.CharField(max_length=5)
    code = models.CharField(max_length=3)

    def __str__(self):
        return '{0} - {1} - {2}'.format(self.name, self.code, self.symbol)

    def short_str(self):
        return '{0} ({1})'.format(self.name, self.symbol)


    class Meta:
        verbose_name_plural = "currencies"

class Game(models.Model):

    title = models.CharField(max_length=256)
    user = models.ForeignKey(User)
    public = models.BooleanField(default=False)
    tournament = models.BooleanField(default=False)
    min_buy_in = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    max_buy_in = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    currency = models.ForeignKey(
        'Currency',
        default=1
    )
    deleted = models.BooleanField(default=False)

    def short_str(self):
        return '{1} ({0})'.format(self.title, self.currency.symbol)

    def __str__(self):
        return '{0} min:{1} max:{2} currency:{3}'.format(self.title, self.min_buy_in, self.max_buy_in, self.currency.symbol)

    class Meta:
        ordering = ('title',)

games/forms.py
from django.forms import ModelForm

from .models import Game

class GameForm(ModelForm):
   class Meta:
      model = Game
      fields = ('title','currency','min_buy_in','max_buy_in')

games/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import GameForm
from .models import Game

@login_required
def list_view(request):
   user = request.user
   form = GameForm(request.POST or None)

   if(request.method == "POST"):
      if(form.is_valid()):
         cleaned = form.cleaned_data
         title = cleaned['title']
         min_buy_in = cleaned['min_buy_in']
         max_buy_in = cleaned['max_buy_in']
         currency = cleaned['currency']
         game = Game (
            title=title,
            min_buy_in=min_buy_in,
            max_buy_in=max_buy_in,
            currency=currency,
            user=user,
            )

         game.save()
         form = GameForm()
         messages.success(request, "Game {0} successfully added".format(game))

   games = (Game.objects.filter(public=True) | Game.objects.filter(user=user)).filter(deleted=False)
   context = {
      'games': games,
      'form': form,
   }
   return render(request, 'games/list.html', context)

@login_required
def delete(request, pk):
   user = request.user

   game = Game.objects.get(pk=pk)

   if(game.user.id != user.id):
      messages.error(request, "Unable to delete {0}. Not the user for this game.".format(game))
      return redirect('games:list')

   game.deleted = True

   game.save()

   messages.success(request, "Game {0} successfully deleted".format(game))
   return redirect('games:list')

games/templates/games/list.html
{% extends 'base.html' %}

{% block title %}pokersessions/detail{% endblock %}
{% block head %}

{% endblock %}
{% block content %}
{% load tz %}
    <h2>Games</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class='btn' type="submit">Add Game</button>
     </form>
      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Min Buy-in</th>
            <th>Max Buy-in</th>
            <th>Public</th>
            <th>Currency</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for game in games %}
          <tr>
            <td>
							{{ game.title }}
            </td>
            <td>
              {{ game.min_buy_in }}
            </td>
            <td>
            	{{ game.max_buy_in }}
            </td>
            <td>
              {{ game.public }}
            </td>
            <td>
              {{ game.currency.short_str }}
            </td>
            <td>
              <form action="{% url 'games:delete' game.id %}" method="get">
              <button class='del'>Delete</button>
              <button class='delyes'>Yes</button>
              <button class='delno'>No</button>
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
{% endblock %}
{% block js %}
<script>
$(document).ready(function() {

  $('.delyes').hide();
  $('.delno').hide();
  $('.del').show();

  $(document).on('click','.del', function(ev) {
    ev.preventDefault();
    $(this).hide();
    $(this).siblings('.delyes').show();
    $(this).siblings('.delno').show();
  });

  $(document).on('click', '.delno', function(ev) {
    ev.preventDefault();
    $(this).hide();
    $(this).siblings('.delyes').hide();
    $(this).siblings('.del').show();
  });
});
</script>
{% endblock %}