accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.edit import CreateView

from .views import RegisterView, IndexView, LoginView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^register/$', RegisterView.as_view() , name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/'}, name='logout'),
]

api/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (ChipStackPokerUpdateJson)


urlpatterns = [
    url(r'^chipstack/(?P<session_id>\d+)/$', ChipStackPokerUpdateJson.as_view(), name='chipstack'),
]

games/urls.py
from django.conf.urls import url
from django.contrib import admin

import games.views


urlpatterns = [
    url(r'^list/$', games.views.list_view, name='list'),
    url(r'^delete/(?P<pk>\d+)$', games.views.delete, name='delete'),
]

pokersessions/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (PokerSessionIndexView, CreatePokerSessionView,
                    AddPokerSessionUpdateView, DeletePokerSessionUpdateView,
                    StartPokerSessionView, ActivePokerSessionView, PokerSessionUserView,
                    PokerSessionDetailView, DeletePokerSessionView)

import pokersessions


urlpatterns = [
    url(r'^$', PokerSessionIndexView.as_view(), name='index'),
    url(r'^(?P<user_id>\d+)/$', PokerSessionUserView.as_view(), name='view'),
    url(r'^create/$', CreatePokerSessionView.as_view(), name='create'),
    url(r'^edit/(?P<session_id>\d+)/add/$', AddPokerSessionUpdateView.as_view(), name='add_update'),
    url(r'^edit/delete/(?P<update_id>\d+)/$', DeletePokerSessionUpdateView.as_view(), name='delete_update'),
    url(r'^start/$', StartPokerSessionView.as_view(), name='start'),
    url(r'^active/$', ActivePokerSessionView.as_view(), name='active'),
    url(r'^(?P<session_id>\d+)/detail/$', PokerSessionDetailView.as_view(), name='detail'),
    url(r'^(?P<session_id>\d+)/delete/$', DeletePokerSessionView.as_view(), name='delete'),
    url(r'^(?P<session_id>\d+)/edit/$', pokersessions.views.edit_poker_session, name='edit'),
]

trackpoker/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from trackpoker import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^pokersessions/', include('pokersessions.urls', namespace='pokersessions')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^locations/', include('locations.urls', namespace='locations')),
    url(r'^games/', include('games.urls', namespace='games')),
    url(r'^$', views.index, name='index'),
]

templates/base.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Track.Poker|{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css"
      integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi"
      crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static "css/gamblr.css" %}" rel="stylesheet">
    {% block head %}{% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
      <a class="navbar-brand" href="#">Track.poker</a>
      <ul class="nav navbar-nav float-lg-right">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="sessionDropdown"
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Session</a>
          <div class="dropdown-menu" aria-labelledby="sessionDropdown">
            <a class="dropdown-item" href="{% url 'pokersessions:index' %}">Index</a>
            <a class="dropdown-item" href="{% url 'pokersessions:active' %}">Active</a>
            <a class="dropdown-item" href="{% url 'pokersessions:start' %}">Start</a>
            <a class="dropdown-item" href="{% url 'pokersessions:create' %}">Create</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'pokersessions:view' user.id %}">Public View</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="configuration"
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Configuration</a>
          <div class="dropdown-menu" aria-labelledby="configurationDropdown">
            <a class="dropdown-item" href="{% url 'locations:list' %}">Locations</a>
            <a class="dropdown-item" href="{% url 'games:list' %}">Games</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
      </div>
    </nav>

    <div class="container">
    {% if messages %}
      {% for message in messages %}
        {% if message.level_tag == 'error' %}
          <div class="alert alert-danger alert-dismissible" role="alert">
        {% elif message.level_tag == 'success' %}
          <div class="alert alert-success alert-dismissible" role="alert">
        {% endif %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{ message }}
        </div>
      {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}TRACK.poker{% endblock %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-3">TRACK.poker</h1>
  <p class="lead">A project for tracking live poker wins and stats</p>
  <hr class="my-2">
  <p>Currently in open alpha.</p>
</div>
{% endblock %}

{% block js %}


{% endblock %}

templates/old_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>WodProg : {% block title %}{% endblock %}</title>

  <!-- Normalize.css -->
  <link rel="stylesheet" src="https://normalize-css.googlecode.com/svn/trunk/normalize.css" />

  <!-- Bootstrap core CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <!-- Custom styles for this template -->
  <link href="#" rel="stylesheet">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>
  <div class="site-wrapper">

    <div class="site-wrapper-inner">

      <div class="cover-container">

        <div class="masthead clearfix">
          <div class="inner-nav">
            <h3 class="masthead-brand">
              <a href='#'>WodProg</a>
            </h3>
            <nav>
              <ul class="nav masthead-nav">
                {% if user.is_authenticated %}
                <li><a href="#">{{ user.email }}</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                <li>
                  <li><a href="{% url 'accounts:register' %}">Register</a></li>
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  {% endif %}
                </li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            {% if messages %}
            {% for message in messages %}
            {% if message.level_tag == 'error' %}
            <div class="alert alert-danger alert-dismissible" role="alert">
              {% elif message.leve2l_tag == 'success' %}
              <div class="alert alert-success alert-dismissible" role="alert">
                {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ message }}
              </div>
              {% endfor %}
              {% endif %}
              <div class="container">
                {% block content %}

                {% endblock %}
              </div>
            </div>
          </div>
        </div>
      </div>


      <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
      <script>
      $(document).ready(function(){
        //Handles menu drop down
        $('.dropdown-menu').find('form').click(function (e) {
          e.stopPropagation();
        });
      });
      </script>
      <script>
      {% block script %}
      {% endblock %}
      </script>
    </body>
    </html>